#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Denovo hit segments: check whether they lie on oligomer (chain-chain) interfaces.
Multi-process + random control (Method B: random same-length segments on same chain).

Inputs:
  - HIT_CSV: denovo-Pfam hit table generated by the ProDive pipeline
  - FASTA:   all denovo sequences used to build HHMs
  - STRUCT_DIR: folder of downloaded denovo structures: XXXX.cif and/or XXXX.pdb

Assumptions:
  1) You built HHM from each denovo chain sequence directly, so Main_Segment "87-98"
     is 1-based indices on that FASTA sequence.
  2) You already have local CIF/PDB files. This script will NOT download anything.
  3) If CIF already contains multiple chains, interface can be computed directly.
  4) If CIF annotation says oligomeric_count>1 but coordinates contain only one protein chain,
     script will WARN that biological assembly may require symmetry generation (not implemented here).

Outputs:
  - Keep all v2 columns
  - Add random-control columns:
      rand_samples,
      rand_mean_interface_frac, rand_std_interface_frac,
      interface_fraction_real,
      rand_zscore, rand_pvalue_ge, rand_enrichment

Dependencies:
  - biopython
  - pandas
  - numpy
  - tqdm (optional)
"""

import os
import re
import sys
import argparse
import traceback
from typing import Dict, Tuple, List, Optional

import numpy as np
import pandas as pd
from Bio import SeqIO
from Bio.Align import PairwiseAligner
from Bio.PDB import PDBParser, MMCIFParser, NeighborSearch
from Bio.PDB.MMCIF2Dict import MMCIF2Dict
from Bio.PDB.Polypeptide import is_aa
from Bio.SeqUtils import seq1

from concurrent.futures import ProcessPoolExecutor, as_completed

try:
    from tqdm import tqdm
except Exception:
    tqdm = None


# ============================================================
# CONFIG
# ============================================================
HIT_CSV = "<PRODIVE_DATA_ROOT>/shared/denovo_global_high_score_summary_fin.csv"
FASTA   = "<PRODIVE_DATA_ROOT>/shared/structures/denovo_structures/all_1927_sequences.fasta"
STRUCT_DIR = "<PRODIVE_DATA_ROOT>/shared/structures/denovo_structures/downloaded_denovo_pdbs"

OUT_CSV = "CHANGE_ME"

# Multi-process
MAX_WORKERS = 16

# Interface definition
DIST_CUTOFF = 5.0  # Angstrom

# Alignment scores for mapping FASTA positions to structure residues
MATCH = 2
MISMATCH = -1
GAP_OPEN = -10
GAP_EXT  = -0.5

# Mapping quality warn threshold
MIN_MAP_FRAC_WARN = 0.80

# Interface classification thresholds (based on mapped-only fraction)
TH_MAJOR = 0.50
TH_PARTIAL = 0.30

# Filter "protein-like" chain
MIN_STD_AA_PER_CHAIN = 10

# Random control
RAND_SAMPLES = 3000
RAND_SEED = 12345  # reproducible



def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Classify de novo-side ProDive fragments by chain-chain interface overlap "
            "and compute same-chain same-length random controls."
        )
    )
    parser.add_argument("--hit-csv", default=HIT_CSV,
                        help="Input de novo-Pfam hit table. No default project path is provided.")
    parser.add_argument("--fasta", default=FASTA,
                        help="FASTA file containing the de novo sequences used to build HHMs.")
    parser.add_argument("--struct-dir", default=STRUCT_DIR,
                        help="Directory containing local CIF/PDB structure files.")
    parser.add_argument("--out-csv", default=OUT_CSV,
                        help="Output CSV path. The output column schema is unchanged from the original script.")
    parser.add_argument("--max-workers", type=int, default=MAX_WORKERS,
                        help="Maximum number of worker processes.")
    parser.add_argument("--dist-cutoff", type=float, default=DIST_CUTOFF,
                        help="Heavy-atom distance cutoff in Angstroms for interface residue detection.")
    parser.add_argument("--min-map-frac-warn", type=float, default=MIN_MAP_FRAC_WARN,
                        help="Mapped-position fraction below which a fragment is labeled LOW_MAP.")
    parser.add_argument("--threshold-major", type=float, default=TH_MAJOR,
                        help="Mapped interface-fraction threshold for InterfaceMajor.")
    parser.add_argument("--threshold-partial", type=float, default=TH_PARTIAL,
                        help="Mapped interface-fraction threshold for InterfacePartial.")
    parser.add_argument("--min-std-aa-per-chain", type=int, default=MIN_STD_AA_PER_CHAIN,
                        help="Minimum number of standard amino-acid residues required for a protein-like chain.")
    parser.add_argument("--rand-samples", type=int, default=RAND_SAMPLES,
                        help="Number of same-chain same-length random windows sampled per fragment.")
    parser.add_argument("--rand-seed", type=int, default=RAND_SEED,
                        help="Base random seed used by the original random-control procedure.")
    parser.add_argument("--match", type=float, default=MATCH,
                        help="PairwiseAligner match score.")
    parser.add_argument("--mismatch", type=float, default=MISMATCH,
                        help="PairwiseAligner mismatch score.")
    parser.add_argument("--gap-open", type=float, default=GAP_OPEN,
                        help="PairwiseAligner gap-open score.")
    parser.add_argument("--gap-ext", type=float, default=GAP_EXT,
                        help="PairwiseAligner gap-extension score.")
    return parser.parse_args()


def _runtime_config_dict():
    return {
        "DIST_CUTOFF": DIST_CUTOFF,
        "MATCH": MATCH,
        "MISMATCH": MISMATCH,
        "GAP_OPEN": GAP_OPEN,
        "GAP_EXT": GAP_EXT,
        "MIN_MAP_FRAC_WARN": MIN_MAP_FRAC_WARN,
        "TH_MAJOR": TH_MAJOR,
        "TH_PARTIAL": TH_PARTIAL,
        "MIN_STD_AA_PER_CHAIN": MIN_STD_AA_PER_CHAIN,
        "RAND_SAMPLES": RAND_SAMPLES,
        "RAND_SEED": RAND_SEED,
    }


def _init_worker(config):
    globals().update(config)


def apply_args(args):
    global HIT_CSV, FASTA, STRUCT_DIR, OUT_CSV
    global MAX_WORKERS, DIST_CUTOFF, MIN_MAP_FRAC_WARN, TH_MAJOR, TH_PARTIAL
    global MIN_STD_AA_PER_CHAIN, RAND_SAMPLES, RAND_SEED
    global MATCH, MISMATCH, GAP_OPEN, GAP_EXT

    HIT_CSV = args.hit_csv
    FASTA = args.fasta
    STRUCT_DIR = args.struct_dir
    OUT_CSV = args.out_csv
    MAX_WORKERS = args.max_workers
    DIST_CUTOFF = args.dist_cutoff
    MIN_MAP_FRAC_WARN = args.min_map_frac_warn
    TH_MAJOR = args.threshold_major
    TH_PARTIAL = args.threshold_partial
    MIN_STD_AA_PER_CHAIN = args.min_std_aa_per_chain
    RAND_SAMPLES = args.rand_samples
    RAND_SEED = args.rand_seed
    MATCH = args.match
    MISMATCH = args.mismatch
    GAP_OPEN = args.gap_open
    GAP_EXT = args.gap_ext


# ============================================================
# Utility functions
# ============================================================
def parse_segment(seg: str) -> Tuple[int, int]:
    m = re.match(r"^\s*(\d+)\s*-\s*(\d+)\s*$", str(seg))
    if not m:
        raise ValueError(f"Bad segment format: {seg}")
    a, b = int(m.group(1)), int(m.group(2))
    if a > b:
        a, b = b, a
    return a, b


def main_hmm_to_pdbid(main_hmm: str) -> str:
    return str(main_hmm).strip().split("_")[0].upper()


def find_structure_file(pdb_id: str, struct_dir: str) -> Tuple[Optional[str], Optional[str]]:
    pdb_id_u = pdb_id.upper()
    pdb_id_l = pdb_id.lower()

    cif_candidates = [
        os.path.join(struct_dir, f"{pdb_id_u}.cif"),
        os.path.join(struct_dir, f"{pdb_id_l}.cif"),
        os.path.join(struct_dir, f"{pdb_id_u}.mmcif"),
        os.path.join(struct_dir, f"{pdb_id_l}.mmcif"),
    ]
    pdb_candidates = [
        os.path.join(struct_dir, f"{pdb_id_u}.pdb"),
        os.path.join(struct_dir, f"{pdb_id_l}.pdb"),
    ]

    cif_path = next((p for p in cif_candidates if os.path.exists(p)), None)
    pdb_path = next((p for p in pdb_candidates if os.path.exists(p)), None)
    return cif_path, pdb_path


def load_fasta_dict(fasta_path: str) -> Dict[str, Tuple[str, str]]:
    d = {}
    for rec in SeqIO.parse(fasta_path, "fasta"):
        desc = rec.description
        first = desc.split()[0]
        base = first.split("|")[0]  # '9D01_1'
        d[base] = (str(rec.seq), desc)
    return d


def extract_chain_candidates_from_desc(desc: str) -> List[str]:
    m = re.search(r"\|Chains?\s+([^|]+)\|", desc)
    if not m:
        return []
    txt = m.group(1).strip()

    auth_chain = None
    m2 = re.search(r"\[auth\s+([A-Za-z0-9]+)\]", txt)
    if m2:
        auth_chain = m2.group(1).strip()

    txt_clean = re.sub(r"\[.*?\]", "", txt).strip()
    parts = [p.strip() for p in txt_clean.split(",") if p.strip()]

    chains = []
    for p in parts:
        tok = p.split()[0].strip()
        if tok:
            chains.append(tok)

    if auth_chain:
        if auth_chain in chains:
            chains.remove(auth_chain)
        chains = [auth_chain] + chains

    out = []
    seen = set()
    for c in chains:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


def safe_three_to_one(resname: str) -> str:
    try:
        r = resname.strip().upper()
        if r == "MSE":
            return "M"
        if r == "SEC":
            return "U"
        if r == "PYL":
            return "O"
        aa = seq1(r)  # unknown -> X
        return aa if aa and len(aa) == 1 else "X"
    except Exception:
        return "X"


def get_chain_std_residues_and_seq(chain):
    residues = []
    seq_chars = []
    keys = []
    cid = chain.id
    for res in chain:
        if not is_aa(res, standard=True):
            continue
        if "CA" not in res:
            continue
        residues.append(res)
        seq_chars.append(safe_three_to_one(res.resname))
        keys.append((cid, res.id))
    return residues, "".join(seq_chars), keys


def list_protein_chains(model):
    out = []
    for ch in model:
        residues, seq, keys = get_chain_std_residues_and_seq(ch)
        if len(residues) >= MIN_STD_AA_PER_CHAIN:
            out.append(ch)
    return out


def build_aligner() -> PairwiseAligner:
    aligner = PairwiseAligner()
    aligner.mode = "global"
    aligner.match_score = MATCH
    aligner.mismatch_score = MISMATCH
    aligner.open_gap_score = GAP_OPEN
    aligner.extend_gap_score = GAP_EXT
    return aligner


def global_align_score(aligner: PairwiseAligner, a: str, b: str) -> Optional[float]:
    alns = aligner.align(a, b)
    if len(alns) == 0:
        return None
    return float(alns[0].score)


def align_map_fasta_to_struct_index(aligner: PairwiseAligner, fasta_seq: str, struct_seq: str):
    """
    Return mapping: fasta_pos (1-based) -> struct_index (0-based position in struct_seq/struct_keys)
    """
    alns = aligner.align(fasta_seq, struct_seq)
    if len(alns) == 0:
        return {}
    aln = alns[0]
    a_blocks = aln.aligned[0]
    b_blocks = aln.aligned[1]

    mapping = {}
    for (a0, a1), (b0, b1) in zip(a_blocks, b_blocks):
        L = min(a1 - a0, b1 - b0)
        for k in range(L):
            fa_pos = (a0 + k) + 1        # 1-based
            st_idx = (b0 + k)            # 0-based
            mapping[fa_pos] = st_idx
    return mapping


def parse_structure_prefer_cif(cif_path: Optional[str], pdb_path: Optional[str]):
    if cif_path:
        try:
            parser = MMCIFParser(QUIET=True, auth_chains=True, auth_residues=True)
        except TypeError:
            parser = MMCIFParser(QUIET=True)
        st = parser.get_structure("X", cif_path)
        return st, cif_path, "mmcif_auth"
    if pdb_path:
        parser = PDBParser(QUIET=True)
        st = parser.get_structure("X", pdb_path)
        return st, pdb_path, "pdb"
    return None, None, "NA"


def parse_structure_mmcif_label(cif_path: str):
    try:
        parser = MMCIFParser(QUIET=True, auth_chains=False, auth_residues=False)
    except TypeError:
        parser = MMCIFParser(QUIET=True)
    st = parser.get_structure("X", cif_path)
    return st


def cif_assembly_need_symgen(cif_path: str) -> Tuple[str, str]:
    try:
        d = MMCIF2Dict(cif_path)
        counts = d.get("_pdbx_struct_assembly.oligomeric_count", None)
        olig_count = "NA" if counts is None else (str(counts[0]) if isinstance(counts, list) else str(counts))

        opers = d.get("_pdbx_struct_assembly_gen.oper_expression", None)
        if opers is None:
            return olig_count, "unknown"

        ops = [str(x).strip() for x in opers] if isinstance(opers, list) else [str(opers).strip()]
        for op in ops:
            if op != "1":
                return olig_count, "yes"
        return olig_count, "no"
    except Exception:
        return "NA", "unknown"


def build_neighbor_search_other_atoms(model, target_chain_id: str):
    atoms = []
    for ch in model:
        if ch.id == target_chain_id:
            continue
        residues, seq, keys = get_chain_std_residues_and_seq(ch)
        if len(residues) < MIN_STD_AA_PER_CHAIN:
            continue
        for res in residues:
            for atom in res.get_atoms():
                elem = getattr(atom, "element", "").strip()
                name = atom.get_name()
                if elem == "H" or name.startswith("H"):
                    continue
                atoms.append(atom)
    if not atoms:
        return None
    return NeighborSearch(atoms)


def residue_is_interface(residue, ns: NeighborSearch, cutoff: float) -> bool:
    if ns is None:
        return False
    for atom in residue.get_atoms():
        elem = getattr(atom, "element", "").strip()
        name = atom.get_name()
        if elem == "H" or name.startswith("H"):
            continue
        if ns.search(atom.coord, cutoff, level="A"):
            return True
    return False


def random_control_stats(prefix_iface: np.ndarray, N: int, L: int, f_real: float, rng: np.random.Generator):
    """
    prefix_iface: prefix sum of interface flags length N+1, prefix_iface[0]=0
    N: chain length (number of residues used in struct_seq/keys)
    L: window length
    f_real: real interface fraction in [0,1]
    """
    if L <= 0 or L > N:
        return (np.nan, np.nan, np.nan, np.nan, np.nan)

    # sample starts uniformly in [0, N-L]
    starts = rng.integers(0, N - L + 1, size=RAND_SAMPLES, endpoint=False)
    # window interface counts by prefix sum
    cnt = prefix_iface[starts + L] - prefix_iface[starts]
    vals = cnt / float(L)

    mu = float(vals.mean())
    sigma = float(vals.std(ddof=0))

    # right-tail p: P(rand >= real)
    ge = int(np.sum(vals >= f_real))
    p_ge = (ge + 1) / (RAND_SAMPLES + 1)

    # z-score
    z = (f_real - mu) / sigma if sigma > 0 else 0.0

    # enrichment
    enrich = (f_real / mu) if mu > 0 else (np.inf if f_real > 0 else 0.0)

    return (mu, sigma, z, p_ge, enrich)


# ============================================================
# Worker: per Main_HMM group
# ============================================================
def process_one_main_hmm_task(main_hmm: str, sub_df: pd.DataFrame, fasta_dict: Dict[str, Tuple[str, str]],
                             struct_dir: str) -> Tuple[str, pd.DataFrame, str]:
    aligner = build_aligner()
    pdb_id = main_hmm_to_pdbid(main_hmm)

    # local RNG per worker & per group (reproducible but different groups different stream)
    # use hash(main_hmm) to decorrelate
    seed = (RAND_SEED ^ (hash(main_hmm) & 0xFFFFFFFF)) & 0xFFFFFFFF
    rng = np.random.default_rng(seed)

    if main_hmm not in fasta_dict:
        out = sub_df.copy()
        out["pdb_id"] = pdb_id
        out["AssemblyClass"] = "NO_FASTA"
        out["FragmentInterfaceClass"] = "NA"
        out["warn"] = "NO_FASTA_ID"
        # random columns
        out["rand_samples"] = RAND_SAMPLES
        out["rand_mean_interface_frac"] = np.nan
        out["rand_std_interface_frac"] = np.nan
        out["interface_fraction_real"] = np.nan
        out["rand_zscore"] = np.nan
        out["rand_pvalue_ge"] = np.nan
        out["rand_enrichment"] = np.nan
        return main_hmm, out, f"[{main_hmm}] NO_FASTA_ID"

    fasta_seq, fasta_desc = fasta_dict[main_hmm]
    chain_candidates = extract_chain_candidates_from_desc(fasta_desc)

    cif_path, pdb_path = find_structure_file(pdb_id, struct_dir)
    st, used_path, mode = parse_structure_prefer_cif(cif_path, pdb_path)
    if st is None:
        out = sub_df.copy()
        out["pdb_id"] = pdb_id
        out["AssemblyClass"] = "NO_STRUCTURE"
        out["FragmentInterfaceClass"] = "NA"
        out["warn"] = "NO_STRUCTURE_FILE"
        out["rand_samples"] = RAND_SAMPLES
        out["rand_mean_interface_frac"] = np.nan
        out["rand_std_interface_frac"] = np.nan
        out["interface_fraction_real"] = np.nan
        out["rand_zscore"] = np.nan
        out["rand_pvalue_ge"] = np.nan
        out["rand_enrichment"] = np.nan
        return main_hmm, out, f"[{main_hmm}] NO_STRUCTURE_FILE"

    olig_count, need_symgen = ("NA", "unknown")
    if used_path and used_path.lower().endswith((".cif", ".mmcif")):
        olig_count, need_symgen = cif_assembly_need_symgen(used_path)

    model = next(st.get_models())
    prot_chains = list_protein_chains(model)
    n_prot = len(prot_chains)

    # fallback if desc has no chain info: use suffix _1/_2
    if not chain_candidates:
        m = re.search(r"_(\d+)$", str(main_hmm))
        if m and n_prot > 0:
            idx = int(m.group(1)) - 1
            if 0 <= idx < n_prot:
                chain_candidates = [prot_chains[idx].id]

    # choose best chain by alignment score
    best = None  # (score, chain_id, struct_seq, struct_keys, struct_residues)
    for ch in prot_chains:
        if chain_candidates and ch.id not in chain_candidates:
            continue
        residues, struct_seq, struct_keys = get_chain_std_residues_and_seq(ch)
        if len(struct_seq) < 5:
            continue
        score = global_align_score(aligner, fasta_seq, struct_seq)
        if score is None:
            continue
        if best is None or score > best[0]:
            best = (score, ch.id, struct_seq, struct_keys, residues)

    chain_id_mode = mode
    if best is None and mode == "mmcif_auth" and used_path and used_path.lower().endswith((".cif", ".mmcif")):
        try:
            st2 = parse_structure_mmcif_label(used_path)
            model2 = next(st2.get_models())
            prot_chains2 = list_protein_chains(model2)
            n_prot2 = len(prot_chains2)

            best2 = None
            for ch in prot_chains2:
                if chain_candidates and ch.id not in chain_candidates:
                    continue
                residues, struct_seq, struct_keys = get_chain_std_residues_and_seq(ch)
                if len(struct_seq) < 5:
                    continue
                score = global_align_score(aligner, fasta_seq, struct_seq)
                if score is None:
                    continue
                if best2 is None or score > best2[0]:
                    best2 = (score, ch.id, struct_seq, struct_keys, residues)

            if best2 is not None:
                st, model, prot_chains, n_prot, best = st2, model2, prot_chains2, n_prot2, best2
                chain_id_mode = "mmcif_label"
        except Exception:
            pass

    if best is None:
        out = sub_df.copy()
        out["pdb_id"] = pdb_id
        out["n_protein_chains"] = n_prot
        out["AssemblyNeedSymGen"] = need_symgen
        out["oligomeric_count_annot"] = olig_count
        out["AssemblyClass"] = "CHAIN_NOT_FOUND"
        out["FragmentInterfaceClass"] = "NA"
        out["parser_file"] = used_path
        out["chain_used"] = "NA"
        out["chain_id_mode"] = chain_id_mode
        out["warn"] = "CHAIN_NOT_FOUND"
        out["rand_samples"] = RAND_SAMPLES
        out["rand_mean_interface_frac"] = np.nan
        out["rand_std_interface_frac"] = np.nan
        out["interface_fraction_real"] = np.nan
        out["rand_zscore"] = np.nan
        out["rand_pvalue_ge"] = np.nan
        out["rand_enrichment"] = np.nan
        return main_hmm, out, f"[{main_hmm}] CHAIN_NOT_FOUND pdb={pdb_id} file={used_path}"

    _, chain_used, struct_seq, struct_keys, struct_residues = best
    N = len(struct_keys)

    # mapping: fasta_pos -> struct_index (0-based)
    map_pos_to_idx = align_map_fasta_to_struct_index(aligner, fasta_seq, struct_seq)

    # build interface set
    if n_prot < 2:
        assembly_class = "MonomerOnly"
        ns = None
    else:
        assembly_class = "MultiChain"
        ns = build_neighbor_search_other_atoms(model, chain_used)

    interface_flags = np.zeros(N, dtype=np.int32)
    if ns is not None:
        for i, (res, key) in enumerate(zip(struct_residues, struct_keys)):
            if residue_is_interface(res, ns, DIST_CUTOFF):
                interface_flags[i] = 1

    # prefix sum for fast window counts
    prefix = np.zeros(N + 1, dtype=np.int32)
    prefix[1:] = np.cumsum(interface_flags)

    contact_res_count_chain = int(interface_flags.sum())

    # prepare output
    out = sub_df.copy()

    seg_start_list, seg_end_list, seg_len_list = [], [], []
    n_mapped_list, mapped_frac_list = [], []
    n_int_list, int_frac_list, int_frac_mapped_list = [], [], []
    cls_list, warn_list = [], []

    # random columns
    rand_mu_list, rand_sd_list = [], []
    f_real_list = []
    rand_z_list, rand_p_list, rand_enrich_list = [], [], []

    for seg in out["Main_Segment"].astype(str).tolist():
        s, e = parse_segment(seg)
        seg_len = e - s + 1

        # mapped indices (0-based) for this segment (only positions that map)
        mapped_idx = [map_pos_to_idx[pos] for pos in range(s, e + 1) if pos in map_pos_to_idx]
        n_mapped = len(mapped_idx)
        mapped_frac = (n_mapped / seg_len) if seg_len > 0 else 0.0

        # interface counts among mapped positions (not requiring contiguity)
        n_int = int(np.sum(interface_flags[mapped_idx])) if n_mapped > 0 else 0

        # original v2-style fractions:
        int_frac = (n_int / seg_len) if seg_len > 0 else 0.0
        int_frac_mapped = (n_int / n_mapped) if n_mapped > 0 else np.nan

        # ---------- Random control (Method B) ----------
        # We need a continuous window length on structure chain.
        # Use L = seg_len (FASTA length) for strict same-length control.
        # But if mapping is poor, still compute random baseline; real f uses mapped positions:
        # define f_real as interface fraction among mapped positions (same as int_frac_mapped)
        f_real = float(int_frac_mapped) if not np.isnan(int_frac_mapped) else np.nan

        if np.isnan(f_real):
            mu = sd = z = p_ge = enrich = np.nan
        else:
            mu, sd, z, p_ge, enrich = random_control_stats(prefix, N, seg_len, f_real, rng)

        # ---------- classification ----------
        warn = ""
        if n_prot < 2:
            cls = "NonInterface"  # no other chains in file
        else:
            if mapped_frac < MIN_MAP_FRAC_WARN:
                cls = "LOW_MAP"
                warn = f"LOW_MAP({mapped_frac:.2f})"
            else:
                if np.isnan(int_frac_mapped):
                    cls = "NA"
                    warn = "NO_MAPPED_RES"
                elif int_frac_mapped >= TH_MAJOR:
                    cls = "InterfaceMajor"
                elif int_frac_mapped >= TH_PARTIAL:
                    cls = "InterfacePartial"
                else:
                    cls = "NonInterface"

        seg_start_list.append(s)
        seg_end_list.append(e)
        seg_len_list.append(seg_len)

        n_mapped_list.append(n_mapped)
        mapped_frac_list.append(mapped_frac)

        n_int_list.append(n_int)
        int_frac_list.append(int_frac)
        int_frac_mapped_list.append(int_frac_mapped)

        cls_list.append(cls)
        warn_list.append(warn)

        # random lists
        rand_mu_list.append(mu)
        rand_sd_list.append(sd)
        f_real_list.append(f_real)
        rand_z_list.append(z)
        rand_p_list.append(p_ge)
        rand_enrich_list.append(enrich)

    # attach columns (keep your v2)
    out["pdb_id"] = pdb_id
    out["chain_used"] = chain_used
    out["n_protein_chains"] = n_prot
    out["AssemblyNeedSymGen"] = need_symgen
    out["oligomeric_count_annot"] = olig_count
    out["AssemblyClass"] = assembly_class
    out["contact_res_count_chain"] = contact_res_count_chain

    out["seg_start"] = seg_start_list
    out["seg_end"] = seg_end_list
    out["seg_len"] = seg_len_list

    out["n_mapped"] = n_mapped_list
    out["mapped_fraction"] = mapped_frac_list

    out["n_interface"] = n_int_list
    out["interface_fraction"] = int_frac_list
    out["interface_fraction_mapped"] = int_frac_mapped_list
    out["FragmentInterfaceClass"] = cls_list

    out["parser_file"] = used_path
    out["chain_id_mode"] = chain_id_mode
    out["warn"] = warn_list

    # random control columns
    out["rand_samples"] = RAND_SAMPLES
    out["rand_mean_interface_frac"] = rand_mu_list
    out["rand_std_interface_frac"] = rand_sd_list
    out["interface_fraction_real"] = f_real_list
    out["rand_zscore"] = rand_z_list
    out["rand_pvalue_ge"] = rand_p_list
    out["rand_enrichment"] = rand_enrich_list

    msg = (f"[{main_hmm}] OK pdb={pdb_id} chain={chain_used} "
           f"nProtChains={n_prot} contactRes(chain)={contact_res_count_chain} "
           f"needSymGen={need_symgen} file={used_path}")
    return main_hmm, out, msg


# ============================================================
# Main
# ============================================================
def main():
    args = parse_args()
    apply_args(args)

    for p in [HIT_CSV, FASTA]:
        if not os.path.exists(p):
            print(f"❌ File not found: {p}", file=sys.stderr)
            sys.exit(1)
    if not os.path.isdir(STRUCT_DIR):
        print(f"❌ STRUCT_DIR not found: {STRUCT_DIR}", file=sys.stderr)
        sys.exit(1)

    print("[INFO] Loading FASTA...")
    fasta_dict = load_fasta_dict(FASTA)
    print(f"[INFO] FASTA sequences: {len(fasta_dict)}")

    print("[INFO] Reading hit CSV...")
    df = pd.read_csv(HIT_CSV, low_memory=False)
    need_cols = ["Main_HMM", "Main_Segment"]
    for c in need_cols:
        if c not in df.columns:
            print(f"❌ CSV missing required column: {c}", file=sys.stderr)
            print("   Found columns:", list(df.columns), file=sys.stderr)
            sys.exit(1)

    groups = [(k, g.copy()) for k, g in df.groupby("Main_HMM", sort=False)]
    print(f"[INFO] Main_HMM groups: {len(groups)}")

    workers = min(MAX_WORKERS, os.cpu_count() or 1)
    print(f"[INFO] Using workers={workers}")

    outs = []
    logs = []

    with ProcessPoolExecutor(max_workers=workers, initializer=_init_worker, initargs=(_runtime_config_dict(),)) as ex:
        futures = [ex.submit(process_one_main_hmm_task, k, g, fasta_dict, STRUCT_DIR) for k, g in groups]

        iterator = as_completed(futures)
        if tqdm is not None:
            iterator = tqdm(iterator, total=len(futures), desc="Processing Main_HMM", unit="grp")

        for fut in iterator:
            try:
                main_hmm, out_sub, msg = fut.result()
                outs.append(out_sub)
                logs.append(msg)
            except Exception as e:
                logs.append(f"[FUTURE_ERROR] {type(e).__name__}: {e}")

    print("\n[INFO] Sample logs:")
    for s in logs[:10]:
        print("  ", s)

    out_df = pd.concat(outs, ignore_index=True)
    print(f"\n[INFO] Writing output CSV: {OUT_CSV}")
    out_dir = os.path.dirname(os.path.abspath(OUT_CSV))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    out_df.to_csv(OUT_CSV, index=False)

    if "FragmentInterfaceClass" in out_df.columns:
        print("\n[SUMMARY] FragmentInterfaceClass counts:")
        print(out_df["FragmentInterfaceClass"].value_counts(dropna=False).head(30))

    if "AssemblyNeedSymGen" in out_df.columns:
        print("\n[SUMMARY] AssemblyNeedSymGen counts:")
        print(out_df["AssemblyNeedSymGen"].value_counts(dropna=False))

    print("\n[DONE]")


if __name__ == "__main__":
    main()
